# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/conb.xdc

# IP: ip/gtwizard_0/gtwizard_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gtwizard_0 || ORIG_REF_NAME==gtwizard_0} -quiet] -quiet
