# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/44497/Desktop/mft_k7_project/test_all_pro_4.12/project_official_1/project_official_1.srcs/sources_1/ip/rom_cg/rom_cg.xci
# IP: The module: 'rom_cg' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/44497/Desktop/mft_k7_project/test_all_pro_4.12/project_official_1/project_official_1.srcs/sources_1/ip/rom_cg/rom_cg_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_cg'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/44497/Desktop/mft_k7_project/test_all_pro_4.12/project_official_1/project_official_1.srcs/sources_1/ip/rom_cg/rom_cg.xci
# IP: The module: 'rom_cg' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/44497/Desktop/mft_k7_project/test_all_pro_4.12/project_official_1/project_official_1.srcs/sources_1/ip/rom_cg/rom_cg_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_cg'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
