# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/44497/Desktop/mft_k7_project/test_all_pro_4.12/project_official_1/project_official_1.srcs/sources_1/ip/clk_buf_40/clk_buf_40.xci
# IP: The module: 'clk_buf_40' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/44497/Desktop/mft_k7_project/test_all_pro_4.12/project_official_1/project_official_1.srcs/sources_1/ip/clk_buf_40/clk_buf_40_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_buf_40'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/44497/Desktop/mft_k7_project/test_all_pro_4.12/project_official_1/project_official_1.srcs/sources_1/ip/clk_buf_40/clk_buf_40.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_buf_40'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/44497/Desktop/mft_k7_project/test_all_pro_4.12/project_official_1/project_official_1.srcs/sources_1/ip/clk_buf_40/clk_buf_40_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_buf_40'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/44497/Desktop/mft_k7_project/test_all_pro_4.12/project_official_1/project_official_1.srcs/sources_1/ip/clk_buf_40/clk_buf_40.xci
# IP: The module: 'clk_buf_40' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/44497/Desktop/mft_k7_project/test_all_pro_4.12/project_official_1/project_official_1.srcs/sources_1/ip/clk_buf_40/clk_buf_40_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_buf_40'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/44497/Desktop/mft_k7_project/test_all_pro_4.12/project_official_1/project_official_1.srcs/sources_1/ip/clk_buf_40/clk_buf_40.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_buf_40'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/44497/Desktop/mft_k7_project/test_all_pro_4.12/project_official_1/project_official_1.srcs/sources_1/ip/clk_buf_40/clk_buf_40_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_buf_40'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
